### ISSUE TITLE
LangChain.LanguageModelProtocol not implemented

### ISSUE THREAD

**Issue by cpursley** [orthagonal/langchainex#28]
When trying to run a Scraper using Bumblebee provider following the README example, I ran into the following error:

```
** (Protocol.UndefinedError) protocol LangChain.LanguageModelProtocol not implemented for %LangChain.Providers.Bumblebee.LanguageModel{provider: :bumblebee, model_name: "distilgpt2", max_new_tokens: 25, temperature: 0.5, top_k: nil, top_p: nil} of type LangChain.Providers.Bumblebee.LanguageModel (a struct). This protocol is implemented for the following type(s): LangChain.Providers.Cohere.LanguageModel, LangChain.Providers.GooseAi.LanguageModel, LangChain.Providers.Huggingface.LanguageModel, LangChain.Providers.NlpCloud.LanguageModel, LangChain.Providers.OpenAI.LanguageModel, LangChain.Providers.Replicate.LanguageModel
```

If you can provide a few pointers about how this works, I might be able to help with a PR once I wrap my head around it all.

**Comment by orthagonal** [comment]
The bumblebee dep was optional because compiling XLA can get tricky on some platforms and most people just want to use the APIs.  To use bumblee you'll want to uncomment the dependencies here: https://github.com/orthagonal/langchainex/blob/primary/mix.exs#L27

On my machine setting it to `
    {:bumblebee, "~> 0.3.0"},
    {:exla, ">= 0.0.0"}
    `
    and mix deps.compile worked.    

However I'm seeing that I have a bunch of timeouts set that are preventing the test from running (it takes a few minutes to download the models), so I'm going to push a working test for bumblebee/scraper and get back to you.

**Comment by cpursley** [comment]
I swore I had Bumblebee and exla working on my machine (at least they were
installed in my apps mix file).

I also had issues with gitex and had to reference the gif repo instead of
hex.

Thanks for the work you’ve put into this library. I’ve already shipped some
production code using it.

**Comment by orthagonal** [comment]
I have a PR for you that demonstrates how it works, except my machine is too humble to handle a decent model (I tested with distilgpt2 so the model itself wasn't smart enough to return parseable JSON).  

https://github.com/orthagonal/langchainex/pull/29/files

It's great to hear people are using this, I have been meaning to get started on v2 and just not had time.

**Comment by cpursley** [comment]
No luck with that model (not due to size, but seems that it errors out before trying to pull):

```
[
  error: %RuntimeError{
    message: "could not match the class name \"LlamaForCausalLM\" to any of the supported models, please specify the :module and :architecture options"
  }
]
"Model Bumblebee NousResearch/Nous-Hermes-Llama2-13b: I had a system malfunction trying to process that request."
```

I did have some decent general success the "google/flan-t5-base" model (but not scraping) while playing around directly with Bumblebee:

https://elixirforum.com/t/configuration-for-text-generation-in-bumblebee/57150/2

^ Any idea how I could get that working (or something similar) with the scraper? An error comes through in the test that looks like this:

```
[
  error: %FunctionClauseError{
    module: LangChain.Providers.Bumblebee,
    function: :prepare_input,
    arity: 2,
    kind: nil,
    args: nil,
    clauses: nil
  }
]
"Model Bumblebee google/flan-t5-base: I had a system malfunction trying to process that request."
```

Also, realized that I needed this in my apps config:

```
config :nx, default_backend: EXLA.Backend
config :langchainex, :bumblebee_enabled, true
```

**Comment by orthagonal** [comment]
The t5 models weren't up to the task either in my experience (you can test it here: https://huggingface.co/google/flan-t5-base). 
I couldn't really find one that would fit on my card and do this task reliably, I have stuck with API services for scraping.  I think the next step for running specific models will be for me to add support for the more ad hoc services like runpod and Accelerate.

**Comment by cpursley** [comment]
Haven't heard of those services, I'll look into them. Thanks for the help. I'll close this for now.

**Comment by cpursley** [comment]
Do you know which hugging face default_model might be best to replace openai for usage with scraper?

**Comment by orthagonal** [comment]
openai is still probably the best but the leaders on this page are closing in on it: https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard
However those models are too big for my machine so I haven't been able to test against them with bumblebee. 
     That's why I'm considering splitting off the API/bumblebee wrapper portion into its own library and enhancing it to support runpod et al, that would let us run private models and data but hosted on expensive hardware: https://www.runpod.io/gpu-instance/pricing
